version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: leave-management-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leavemanagement
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - leave-management-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leave-management-app
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leavemanagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - leave-management-network

networks:
  leave-management-network:
    driver: bridge

volumes:
  mysql-data: