apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-management
  namespace: default
  labels:
    app: leave-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leave-management
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: leave-management
    spec:
      containers:
      - name: leave-management
        image: kastrov/leave-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/leavemanagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /login
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /login
            port: 8090
          initialDelaySeconds: 90
          periodSeconds: 30
      restartPolicy: Always